Handle error responses more succinctly

diff --git a/gpt b/gpt
--- a/gpt
+++ b/gpt
@@ -50,22 +50,16 @@ PROMPT=$* jq -f /dev/fd/3 -s -R \
   | curl -d @- -f -m 30 -s -H @/dev/fd/4 "$API" \
   | jq -e -f /dev/fd/5 -r \
   | fmt -s -w 76
-set -- $? ${PIPESTATUS[@]}
+set $? ${PIPESTATUS[@]}
 
-if [[ $1 -ne 0 ]]; then
-  case $3 in
-    0)
-      echo "Invalid response from model"
-      ;;
-    6|7)
-      echo "Failed to connect to host"
-      ;;
-    28)
-      echo "Content generation timed out"
-      ;;
-    *)
-      echo "Content generation failed: $3"
-      ;;
-  esac >&2
-  exit 1
-fi
+if [[ $3 -eq 6 ]] || [[ $3 -eq 7 ]]; then
+  echo "Failed to connect to host"
+elif [[ $3 -eq 28 ]]; then
+  echo "Content generation timed out"
+elif [[ $3 -ne 0 ]]; then
+  echo "Content generation failed: $3"
+elif [[ $4 -ne 0 ]]; then
+  echo "Invalid response from model"
+fi >&2
+
+exit $(($1 != 0))
diff --git a/gpt-stream b/gpt-stream
--- a/gpt-stream
+++ b/gpt-stream
@@ -44,26 +44,20 @@ PROMPT=$* jq -f /dev/fd/3 -s -R \
   | sed -n -u 's/^data:\s*//p' \
   | jq -e -f /dev/fd/5 -j -R --unbuffered \
   | fold -s -w 76
-set -- $? ${PIPESTATUS[@]}
+set $? ${PIPESTATUS[@]}
 
 if [[ $5 -ne 4 ]]; then
   printf '\n'
 fi
 
-if [[ $1 -ne 0 ]]; then
-  case $3 in
-    0)
-      echo "Invalid response from model"
-      ;;
-    6|7)
-      echo "Failed to connect to host"
-      ;;
-    28)
-      echo "Content generation timed out"
-      ;;
-    *)
-      echo "Content generation failed: $3"
-      ;;
-  esac >&2
-  exit 1
-fi
+if [[ $3 -eq 6 ]] || [[ $3 -eq 7 ]]; then
+  echo "Failed to connect to host"
+elif [[ $3 -eq 28 ]]; then
+  echo "Content generation timed out"
+elif [[ $3 -ne 0 ]]; then
+  echo "Content generation failed: $3"
+elif [[ $5 -ne 0 ]]; then
+  echo "Invalid response from model"
+fi >&2
+
+exit $(($1 != 0))
diff --git a/translate b/translate
--- a/translate
+++ b/translate
@@ -19,18 +19,14 @@ curl -f -m 30 -s -F file="@$1" -F model="$MODEL" -F response_format=text \
      -H @- "$API" <<< "Authorization: Bearer $KEY" \
   | sed -e "y/‘’“”/''\"\"/" -e 's/…/.../g' -e 's/ \?— \?/ - /g' \
   | fmt -s -w 76
+set $? ${PIPESTATUS[@]}
 
-if set -- $? && [[ $1 -ne 0 ]]; then
-  case $1 in
-    6|7)
-      echo "Failed to connect to host"
-      ;;
-    28)
-      echo "Translation timed out"
-      ;;
-    *)
-      echo "Translation failed: $1"
-      ;;
-  esac >&2
-  exit 1
-fi
+if [[ $2 -eq 6 ]] || [[ $2 -eq 7 ]]; then
+  echo "Failed to connect to host"
+elif [[ $2 -eq 28 ]]; then
+  echo "Translation timed out"
+elif [[ $2 -ne 0 ]]; then
+  echo "Translation failed: $2"
+fi >&2
+
+exit $(($1 != 0))
